version: 2

builds:
  - main: ./cmd/bgg-tui
    binary: bgg-tui
    ldflags:
      - -s -w -X github.com/hiroaqii/bgg-tui/internal/tui.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: bgg-tui
    binaries:
      - bgg-tui
    repository:
      owner: hiroaqii
      name: homebrew-bgg-tui
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/hiroaqii/bgg-tui"
    description: "TUI application for BoardGameGeek"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
